### ISSUE TITLE
state prove failed.

### ISSUE THREAD

**Issue by LiRiu** [hyperoracle/zkgraph-cli#35] opened 2023-12-28 04:40 UTC
It seems that the state prove has failed.
### ENV
- zkgraph-lib: v1.0.1
- zkgraph-api: v1.0.3
- zkgraph-cli: v1.0.0
- CompilerServerEndpoint: `http://compiler.dev.hyperoracle.io/compile`

### Reproduce
1. npm init zkgraph@latest
2. Follow the instructions to initialize the storage demo project.
3. modify zkgraph.config.ts with a valid privateKey
4. `npm run compile && npm run setup`
5. `npm run prove -- 4971020 6370902000000003336530047e5ec3da40c000000000068f1888e6eb7036fffe --prove`
6. zkgraph will have the following error messages.
![image](https://github.com/hyperoracle/zkgraph-cli/assets/103174898/e68ab32e-a61a-4a09-8a72-40fde530e423)

**Comment by lightmanM** [comment] 2024-01-04 00:50
Seems to be the zkwasmhub issue, the last time i checked it was fine. Close the issue until been reproduced.

**Closed by lightmanM** 2024-01-04 00:50 UTC
